services:
  
  yogesh-selenium:
    image: yogesh3688/selenium
    
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE=product-search.xml
    volumes:
      - ./output/yogesh-selenium-output:/home/selenium-docker/test-output
